### PR TITLE
Fix Android SDK 31 blur freeze

### PR DESCRIPTION
**Pull request by gleb-skobinsky**
This pull request fixes https://github.com/chrisbanes/haze/issues/77.
The rendering freeze appears to be related to the JNI interop level, as the native layer tries to optimize out changes if they are translated but no position changes are involved.

### CODE REVIEW

**Comment by gleb-skobinsky** [comment]
Unfortunately, it turns out this fix works for samples where position is updated (credit card), but still doesn't for samples where the background is updated, but the position remains the same (scaffold).

**Comment by chrisbanes** [comment]
> Unfortunately, it turns out this fix works for samples where position is updated (credit card), but still doesn't for samples where the background is updated, but the position remains the same (scaffold).

I don't think we can re-enable this if static content isn't working. I'll play around with this over the weekend and see if we can add something to force the RenderNode to invalidate.

**Comment by gleb-skobinsky** [comment]
> > Unfortunately, it turns out this fix works for samples where position is updated (credit card), but still doesn't for samples where the background is updated, but the position remains the same (scaffold).
> 
> I don't think we can re-enable this if static content isn't working. I'll play around with this over the weekend and see if we can add something to force the RenderNode to invalidate.

Yes, this is not a solution that produces a consistent result. Sorry for the fuss. Need to investigate further

**Comment by chrisbanes** [comment]
Closing this, as the changes in `main` supersede this. SDK 31 still isn't working though.

**Pull request closed without merging**
