### PR TITLE
fix: modified alpha value of the final vec4 to 1.0

### PR DESCRIPTION
**Pull request by Dynaruid**
Hello,

I've identified and resolved an issue within the haze library's shader that was causing an unintended visual effect. The core of the problem was related to the final vec4 object's alpha value produced inside the shader. Specifically, the alpha value was not appropriately adjusted, resulting in the blurred image not fully obscuring the foreground, thus allowing the unblurred foreground image to be visible alongside the blur effect.

To address this, I modified the shader code to set the alpha value of the final vec4 to 1.0 just before it's returned. This adjustment ensures that the resulting blurred bitmap completely covers the foreground, allowing for a more natural and visually appealing presentation of the blur effect.

This change does not affect any other functionality of the shader or the haze library and improves the visual quality of the blur effect by ensuring it behaves as expected without unintended foreground visibility.

I believe this improvement can benefit others who are using the haze library for their projects, and I hope you will consider merging this pull request to incorporate the fix into the main branch.

### CODE REVIEW

**Comment by chrisbanes** [comment]
Nice! Thanks for the fix!

**Review by chrisbanes — DISMISSED** [review]

**Comment by chrisbanes** [comment]
Ah, the screenshot tests need to be updated. Can you run `./gradlew recordRoborazziJvm` and upload the changes?

**Comment by Dynaruid** [comment]
> Ah, the screenshot tests need to be updated. Can you run `./gradlew recordRoborazziJvm` and upload the changes?

OK, I've updated the screenshot tests and uploaded them

**Comment by Dynaruid** [comment]
Upon further reflection, I have come to realize that my solution may not be the most appropriate or effective method to address the fundamental issue. My approach involved forcibly fixing the alpha value to obscure the foreground, which seemed to resolve the issue at a glance. However, I overlooked the possibility that the graphics input into the shader might lack RGB values, leading to transparent pixels turning black and, consequently, producing an incorrect blur effect.
 I am currently exploring alternative approaches to effectively solve the problem.

**Pull request closed without merging**
